# Generated by Django 5.2.8 on 2025-11-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('SellerID', models.CharField(max_length=7)),
                ('Price', models.FloatField()),
                ('WarrantyMonths', models.IntegerField()),
                ('Ratings', models.FloatField()),
                ('DeliveryDate', models.DateField()),
            ],
        ),
    ]
